site_name: API Reference Manual
site_url: https://nocturneent.github.io/Developers-Documentation/
repo_name: NocturneEnt/Developers-Documentation
repo_url: https://github.com/NocturneEnt/Developers-Documentation/

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  palette:
    primary: "Deep Purple"
    accent: "Deep Purple"

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - codehilite
